### ISSUE TITLE
Support returning to search results

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/cantus#136]
> We need a "return to results" button. Currently if you do a search and get 249 hits, after you click on one of the hits and view the page you lose your list of results.

Refs #132

**Comment by wabain** [comment]
There are two ways to mitigate the root issue of search results disappearing without adding a return to results button.

1. Clicking on a search result shouldn't trigger a page reload; it should just jump to the result.
2. The search query should be added to the URL's query string, so that search queries would persist over page loads.

I plan to implement both of these. With those in place, I think it would be sufficient for there to be an indicator that there are search results which is visible when the search pane isn't active. Hacked together example:

![search_badge_example](https://cloud.githubusercontent.com/assets/7651435/7861297/4a214d5c-051d-11e5-9ac3-7041a2cfe339.png)

(The exact form of that indicator can be revised.)

Mentioning @ahankinson to review.

**Comment by ahankinson** [comment]
This looks OK to me. Perhaps make the indicator red with white text to make it more apparent?

It's also worth mentioning that on Firefox it seems to trigger a reload, but not on Chrome or Safari.

**Comment by wabain** [comment]
Actually on the develop head it doesn't seem to be triggering a reload at all. It is re-rendering the views where it might be better if it didn't, though. I'll look into it.
