### ISSUE TITLE
Bring back the table format for MSS

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#196]
For displaying the current Manuscripts, I liked having the table format -- it was pretty clean and contained valuable information about the MSS (# of chants, etc.) The unordered list looks a bit messy.

I would be willing to submit a Pull Request to re-format it back to the table, but wanted to check first to see if this was actually a conscious decision. @vigliensoni? @wabain?

**Comment by wabain** [comment]
I guess it was under-considered but yes, it was a conscious decision on my part. I went ahead with the reformatting in part because I've grown to dislike the table display pretty strongly. The basic problem I think was that having a table presents you with all the information at once with no hierarchy of significance, which can be disorienting since the Manuscripts page is the main entry point for browsing the manuscripts.

Maybe a tiled view would work better than the list? The "most viewed sources" tiles at <http://cantus.uwaterloo.ca/> could be a place to start, although we would need to fit in more information. OTOH a table format would make it easier to compare information between MSS, so ultimately it's a value judgment.

**Comment by ahankinson** [comment]
I'm not sure what you mean by "Hierarchy of significance." 

An unordered list just looks messy, especially if it grows to any significant length. Without headers or labels, people are never really sure what bit of information they're looking at. 

If you don't like the table format I'd be willing to go with something else if you think of something, but I think the unordered list is not the way to go.

**Comment by ahankinson** [comment]
Hm... on second thought, I'm not sure if I like the tiles -- there's a lot of truncated information in them.

**Comment by fujinaga** [comment]
I suggest that we present the different versions (mock-up screenshots would do), to the researchers (Jennifer, Debra, et al.) and listen to their feedback.

Ich

**Comment by wabain** [comment]
Agreed, if we went with tiles we'd need to avoid truncating.
