### ISSUE TITLE
Single neume search

### ISSUE THREAD

**Issue by fujinaga** [DDMAL/cantus#197]
Neume search in OMR Search (Salzinnes): single neume search for "virga" and "punctum" do not work.

**Comment by wabain** [comment]
@ahankinson Trying to make sure I understand the expected behavior here:

 - Currently we index ngrams for 2 <= n <=10, where n is the number of notes. So for instance for [this scandicus](https://github.com/DDMAL/cantus/blob/e700f9f92dece6b25c4e597ae9725a09dc6860b5/public/data_dumps/mei/salz/pitches_001.mei#L306), which corresponds to three notes with pitches `gab`, we index bigrams with pitches `ga` and `ab` (as well as ones which overlap with the preceding and subsequent neumes).

 - We *don't* want to start indexing unigrams in general, but we do want to index neumes which correspond to a single note so they can show up in single neume search. Therefore, they need to be treated as a special case.

If that's right, then it seems to me that thinking in terms of the current search interface, I shouldn't be indexing pitch data for these neumes, since we don't care about single notes. Is that correct, at least in the short term?

**Comment by ahankinson** [comment]
Yes, neume names only, not pitches.
