### ISSUE TITLE
Wrong title

### ISSUE THREAD

**Issue by fujinaga** [DDMAL/cantus#199]
I think the title of the manuscript at the top of the page should be what's in red in the Manuscripts page, e.g., "Salzinnes, CDN-Hsmu M2149.L4" not "Halifax (Canada), St. Mary’s University - Patrick Power Library, M2149.L4 1554, 1554-5"

**Comment by ahankinson** [comment]
This is the title given by CANTUS:

"Halifax (Canada), St. Mary’s University - Patrick Power Library, M2149.L4 1554"

http://cantus.uwaterloo.ca/source/123723

If we want to change it, we should change it upstream. I don't want our database to get out of sync with CANTUS.

**Comment by fujinaga** [comment]
Ok. How about putting the Siglum there instead, e.g., CDN-Hsmu M2149.L4 ?

**Comment by ahankinson** [comment]
Maybe this is something that Debra or Jennifer should weigh in on? If we go with siglum, we'll also have "CH-SGs 390" and "CH-SGs 391", which isn't very descriptive to anyone but the few people who know this siglum by heart.

Salzinnes is also a (relatively) unimportant MSS in the grand scheme of things, so "CDN-Hsmu M2149.L4" may not be understood by many people.

**Comment by fujinaga** [comment]
Yes, let's ask them.

**Comment by wabain** [comment]
The format used in the current version of the Manuscripts page is "[provenance], [siglum]." I went with it because it corresponded as closely as possible to the format Gabriel had used. Would it generate confusion to use that in the header?

 - Salzinnes, CDN-Hsmu M2149.L4 [versus Halifax (Canada), St. Mary’s University - Patrick Power Library, M2149.L4 1554]
 - St. Gallen, CH-SGs 390 [versus Sankt Gallen, Stiftsbibliothek, 390]
 - St. Gallen, CH-SGs 391
 - Utrecht, NL-Uu 406

Could go for a variation like "[siglum], [provenance]" too.

I guess my question would be whether people will find the CANTUS title meaningful at first glance when the library location differs from the provenance. But I guess the Salzinnes MS might just be an awkward corner case in that respect.

**Comment by ahankinson** [comment]
I'm ok with [provenance], [siglum].
