### ISSUE TITLE
Reconstruct user view with URL

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#243]
There should be enough information stored in the URL to have the user re-construct a search and position in a MSS. The URL should be exposed in the 'link' box.

**Comment by wabain** [comment]
Refs DDMAL/diva.js#288.

When that's fixed, most of the page's state can be reliably permalinked, with the exception of some UI state in the folio/search panes.

There's also an awkward bug where if you're reconstructing an OMR search the first result gets focused, rather than whatever page you meant to reference. It's probably possible to stick a special-cased check somewhere to keep that from happening.

**Comment by jeromepl** [comment]
I think this can be closed, can anyone confirm?
From what I see the view seems to be reconstructed fine, and the url in the 'link' box contains all required query parameters.

**Comment by wabain** [comment]
On dev-cantus I can still reproduce the case where you perform an OMR search and then scroll to a page other than that where the first result is.
