### ISSUE TITLE
Provide volpiano with text underlay

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#247]
Syllabification of text with the volpiano -- talk to Jan about how he did this, figure out how to index it. http://cantus.uwaterloo.ca/chant/270053

Also see: #246

**Comment by jeromepl** [comment]
Got some clarification on this issue at the cantus meeting:
- In the volpiano, 2 spaces indicates the end of a syllable and 3 spaces indicates the end of a word.
- Jan used a syllabifier in order to split the chant texts.

My guess is that if we used a monospaced font the same width as the volpiano font, we could align both perfectly.

**Comment by wabain** [comment]
The way the alignment is done on cantus.uwaterloo is actually pretty clever. It would be nice if it handled overflows better, but to some extent that's a problem you'd get with monospaced fonts too.
