### ISSUE TITLE
Actions encoded as query parameters in URL

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#250]
To discuss:

We have URLs that look like this:

http://dev-cantus.simssa.ca/manuscript/133/?folio=006r&search%5Btype%5D=all&search%5Bquery%5D=domine

This does not follow REST, since the action ('search type') is encoded as a query parameter, not as a resource. 

This breaks content negotiation as well, since appending `&format=json` (or asking for a response type of `application/json`) for this endpoint brings back the JSON format of the MSS, _not_ JSON-formatted search results.

I know this will be a tricky issue to resolve, so I think a discussion is warranted.

**Comment by wabain** [comment]
Getting to this just a little late...

I wouldn't say that "search type" is an action in the sense that something like `/cgi.php?object=accounts&action=post` would be. As I see it, the problem is that the HTML resource those URLs refer to is built using complex, non-hierarchical data that we don't really want to represent as a single JSON document. We're specifying the folio, chant, and search parameters and those correspond to distinct JSON endpoints.

I think the best semantic fit for this would be fragment identifiers; they're dependent on the media type and [can point to](http://tools.ietf.org/html/rfc3986#section-3.5)

>   some portion or subset of the primary
    resource, some view on representations of the primary resource, or
    some other resource defined or described by those representations.

Unfortunately, recoding this as a fragment identifier would probably cause a lot of issues - it conflicts with Diva's links, for one thing, and there are too many ways of accidentally changing the fragment in HTML.

So the alternative I think we should go with is just handling this through content negotiation and sending a 303 or 404 for JSON requests to those endpoints. If we redirect it would just be to the manuscript, e.g. http://dev-cantus.simssa.ca/manuscript/133/ , which should also be a IIIF manifest that tells you how to search, select a specific folio, etc.
