### ISSUE TITLE
Transition image serving to IIIF

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#261]
Right now we are using our own copies of the images for serving on Cantus. In the case of the St. Gall Manuscripts, we should move to using the manifest provided by e-codices. In the case of the Salzinnes we will probably need to create a IIIF manifest for it, but we will still need to host the images.

For Utrecht 406 we will be able to use the DIAMM manifest when it stabilizes.

Right now we are using the 'old' Diva.js JSON files for serving the file structure, so we will need to deprecate that. It may mean upgrading our diva installation to 4.0 or (potentially) 5.0.

This will be a fairly large task.

**Comment by wabain** [comment]
So the steps here:

 - [ ] Upgrade Diva (hopefully to 5.0). The awkward bit will be making any upgrades needed to the hacky toolbar alterations. Workarounds for the viewport tag and the Chrome zooming bug can be removed.
 - [ ] Create a IIIF manifest for Salzinnes. The Diva manifest utilities currently aren't IIIF aware, so this might be a bit awkward. [IIIF-prezi](https://github.com/IIIF/iiif-prezi) could help.
 - [ ] Point to the correct manifests on the client. That's currently all hard-coded, changing is pretty straightforward.

**Comment by wabain** [comment]
I found [some code](https://github.com/DDMAL/cantus/blob/aea8f56c5b1aa92f998a8ef31df39e7e7e26b230/public/cantusdata/frontend/public/js/app/manuscript-detail/DivaView.js#L416) which will definitely break when transitioning to Diva 5. I'll make sure there's a less fragile way to do what it's doing.

**Comment by ahankinson** [comment]
IIIF manifests for Salzinnes have been created.

Manifests are available on Gallica for [Paris 12044](http://gallica.bnf.fr/iiif/ark:/12148/btv1b6000531z.r/manifest.json) and [Paris 15181](http://gallica.bnf.fr/iiif/ark:/12148/btv1b8447768b/manifest.json).

Manifests for [Utrecht 406](https://beta.diamm.ac.uk/sources/1355/manifest/) is available on DIAMM

**Comment by jeromepl** [comment]
Decided to go with Diva 4 for now since the Diva 5 release is only planned for August

**Comment by ahankinson** [comment]
It could be useful to use Cantus as an opportunity to shake out some bugs in Diva 5

**Comment by jeromepl** [comment]
I think that is a good idea, but I am going to stick with Diva 4 for a little while just to have time to finish the more pressing issues of Diva 5.

I am working on transitioning to IIIF right now and I am running into some issues with the folio numbers. Currently, CU figures out the folio by reading the file name. However, the file names are inconsistent across libraries and even our own salzinnes manifest differs from the previous file names (which used the convention [siglum slug]_[folio number].[extension]).
Now since some manuscripts like salzinnes have folios of the type 001r, and others like St Gallen 391 have simply numbers from 1 to the page count, we should probably figure out some convention that I can use to convert from a page index to a folio name.
Note that some manuscripts also have bindings (like the e-codices version of St. Gallen 391). Those will be hard to detect. (I guess we can manually remove them in the IIIF manifests?)

**Comment by jeromepl** [comment]
It is worth noting that everything in Solr has also been indexed using those folio numbers, changing them would mean reindexing everything. In fact, those folio numbers come directly from the Cantus Database data dumps.

**Comment by ahankinson** [comment]
Ah, yes. Tricky.

We might want a way to read in a IIIF manifest, get the image URLs, and then map them to a page number somehow. Maybe a screen in the Django admin? Import manifest, list the URLs to images on the left, with a list of text input boxes on the right.

You might even be able to show a thumbnail of the image since you will have the IIIF image urls.

**Comment by jeromepl** [comment]
I think that could be possible.

Do you see any problems with directly changing the manifest files with that django admin page? It would simplify this a lot. Simply enter your mapping in the input boxes, click save, and all the "label" tags in the IIIF manifest would get updated. That way no existing code has to be edited.

**Comment by ahankinson** [comment]
There are two issues, both of them problematic.

The first is that a manifest essentially gets us 90% of the way there, in terms of linking images to semantic content. We simply give a URL to an image, map the CANTUS content to the pages, and then we're done. We don't need to then re-generate manifests, and do all sorts of stuff to re-generate our own manifests based on, e.g., an e-Codices manifest.

The second thing, though, is that changes to the manifest can break the site in horrible ways. If they update the manifest with new file names, or new labels, our site is broken. Welcome to the wonderful world of the semantic web. :-/

Thoughts? I think we should discuss this here before deciding on a course of action.

**Comment by jeromepl** [comment]
No matter what we do, there is no way to avoid repercussions of libraries changing their manifests' content. If we just use a link to their manifest instead of downloading a copy of it, then we are still at risk of them changing the location of it. At least we can avoid depending on the label names by using page indexes to map our own folio names.
The only way around that would be to host a copy of all those manuscripts (like how we are doing it right now).

I am not sure I understand your first issue. What is the 10% remaining that we need to address?

Something to note here is that part of the problem is due to the Cantus DB having their own naming convention for folio names. Also, in the data dumps, there is a field called "Image link" but we cannot use it as it does not refer to the IIIF image link but rather to, for example, a [link to e-codices](http://www.e-codices.unifr.ch/en/csg/0390/006). We also cannot just use the folio names in the data dumps to do the mapping since pages that don't contain chants will not be referenced anywhere.

**Comment by ahankinson** [comment]
So if we download a manifest, extract the image URLs, and then re-create our own manifests based on this, we gain control, but this also requires our own manifest creation system. 

If we just use the manifests as-is, we can just harvest them, but if they ever change (different images, different labels) we will have to re-map them, and in the meantime our site will be broken.

So I think the best thing to do is to store the manifest on our side and cache it.

Yeah, the 'image link' should be ignored. This is just a link to the website where the source is published.

**Comment by jeromepl** [comment]
So we store it on our side and I create a tool to map each page index to a folio name (effectively changing the "label" tags in the manifest). The person using that tool would need to follow the cantus DB data dumps in order to map everything correctly. Does that sound acceptable?

**Comment by ahankinson** [comment]
What do you mean by "follow" the data dumps?

**Comment by jeromepl** [comment]
Here is the process flow right now:
Diva receives a manifest location. When Cantus triggers the method divaInstance.getCurrentPageFilename(), diva returns the label since it is a IIIF manifest. Using this label, Cantus tries to calculate the folio name to use. This folio name is what is sent to the server when querying all chants on the current page.

So if the mapping we create does not match the folio names in the data dumps from CantusDB, we won't get any chants back. (Also, search results' links won't work)

**Comment by ahankinson** [comment]
Can we store the URI for the image in Solr? That might be a more future-proof method of querying for all the chants on a particular image.

**Comment by ahankinson** [comment]
Also, shouldn't `getCurrentPageFilename()` for a IIIF manifest in Diva return the URI, not the label?

**Comment by jeromepl** [comment]
I do not think storing the URI in Solr is better. It would be more robust, but if we do that, we still need a client side method of converting from URI to folio and vice-versa. Also keep in mind not all pages have something indexed in Solr: pages with only a picture, for example.

Here is an idea: We stop displaying the Folio name in CU. Instead, we use the regular page number provided by diva. Then, in Solr, we add a field called "page_index" which we can use for all queries. Only thing we need to do is figure out the best way to add that field in Solr. It is a shame that Cantus DB doesn't have this indexed already.

**Comment by jeromepl** [comment]
As for `getCurrentPageFilename()`, I am too unfamiliar with Diva and IIIF to decide on this. Is the "label" field in IIIF always unique? If it is then it makes for both the URI and the label to be sent back, it is just preference at this point.

If you look in ddmal/diva.js#314, @wabain left a note on that method saying it is unclear what is expected of it with IIIF.

**Comment by ahankinson** [comment]
A label is not unique; you could have two images of the same page (for example, in natural and UV light exposures). The IIIF image URL, thought, would be unique, and is most analogous to a filename.

**Comment by jeromepl** [comment]
Summary of a discussion I just had with @ahankinson:

I will make a web interface that people can use to map image URIs (taken from the IIIF manifest) with the folio names (taken in the Cantus DB data dumps). This tool could also update the Solr DB directly. All code should then use the URIs as a key to access the chants in the Solr database. Furthermore, a change needs to be done in Diva so that the `getCurrentPageFilename()` returns the URI instead of the label.

**Comment by ahankinson** [comment]
Amazing!!!!!

Thank you!

**Comment by jeromepl** [comment]
@wabain, the code that you said was going to fail is indeed failing when trying to upgrade to Diva 5. Did you ever get around to creating a way to do what that code was trying to do?
Basically *averageHeights* and *averageWidths* seem to not exist anymore in the diva settings.

**Comment by wabain** [comment]
I think going through the DOM objects for the highlights would be less fragile than the current code. It should be possible to rig something up using `divID`, if I remember correctly. It would have been nice to expose a decent public API for position information, but the internals representations still had too many warts for that.
