### ISSUE TITLE
Additional SSH keys when instantiating with Vagrant

### ISSUE THREAD

**Issue by napulen** [DDMAL/cantus#395]
Currently, the container auto-generates an SSH key and deploys in the cloud using that key.

It is likely that the generated SSH key will be lost for various reasons. It would be best to also enable the SSH keys in the cloud system to log in to the container once it is deployed.

**Comment by napulen** [comment]
We need a routine, arguably in the `etc/provision` folder, that takes care of adding the relevant public `ssh` keys of other developers who need access to the cantus ultimus machine.

I don't foresee a problem with just copying an `SSH` key to the repo, but maybe the more important problem to solve is: *Which SSH keys do you copy to the VM and where do you get them from?* It'd be nice to devise some system for this.

Some relevant resources:
- https://stackoverflow.com/questions/30075461/how-do-i-add-my-own-public-key-to-vagrant-vm
- https://www.vagrantup.com/docs/vagrantfile/ssh_settings

**Comment by dchiller** [comment]
Status update

- Can successfully add custom ssh public keys to a vagrant box either during the provisioning or after provisioned and running. 
- Have a basic understanding of what the current ansible-based process for adding keys to dev and prod environments is, and think it will work (I replicated a basic version of the ansible process locally, and I can use it to interact with the vagrant ssh box)

I would recommend that we piggy-back on the ansible-driven process in ddmal/operations repo so that ssh keys to the vagrant box are always aligned with updates to ddmal organization keys. 

After poking around, here are the questions that we need to answer to determine the exact approach to take:
1. We want all individuals with keys in a certain group to be able to ssh to the vagrant box. Do we want them all to have their own user within the virtual machine? I think, if I am thinking about this like a container, that they can all just use the same default user. Thoughts?
2. Do we want to tie key updates to provisioning. In other words, do we want to reprovision every time we want to change keys? Or do we want to adjust keys while we keep the box running? 
3. Currently, the private key to the vagrant vm is stored on the host machine and password authentication is allowed to ssh to the vagrant box (with a default password of `vagrant`). In other words, it's fairly trivial to ssh into the running vagrant box if you have access to the host machine. Given that access to the host is fairly secure, this probably isn't a problem? But we could also make it so that key authentication is required and that no useful private keys are stored on the virtual machine.

**Comment by napulen** [comment]
1. Either can work, both have pros and cons: maybe the easiest is to share the default user.
2. Not sure about this one. Maybe the second one.
3. For the time being, let's disable the password ssh login
