### ISSUE TITLE
Mapped folio shows as unmapped

### ISSUE THREAD

**Issue by eliwaksbaum** [DDMAL/cantus#476]
Right now F-Pnm lat. 15181 shows the chants when you look at it, but in the admin view and the map_folios view it's listed as unmapped

**Comment by eliwaksbaum** [comment]
well it eventually fixed itself. but it took a bit

**Comment by dchiller** [comment]
Probably, this is because the is_mapped attribute is not switched to True until the mapping process (writing to postgres) is complete. Perhaps that is confusing? We could have some mapping in progress designation? 

How long do you think it took though? The mapping to postgres shouldn't take longer than a minute or two... (of course, we are discussing general slow speeds elsewhere that may impact)

**Comment by eliwaksbaum** [comment]
I would say closer to five minutes. I think a mapping in progress would be nice, especially since mapping and then returning to the page to see "not mapped" can make you worry it didn't go through

**Comment by dchiller** [comment]
Agreed

**Comment by napulen** [comment]
There should be some sort of state for this already? I vaguely remember you can find out it is in progress. If not, shouldn't be difficult to implement it.

**Comment by napulen** [comment]
My bad then. Ok, so the enum sounds good.

**Comment by dchiller** [comment]
perfect! will do.

**Comment by dchiller** [comment]
Addressed by #510
