### ISSUE TITLE
partial images for D-KA Aug LX

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/cantus#520]
The images for D-KA Aug LX only show up partially, like so:

![image](https://user-images.githubusercontent.com/67451875/178637784-d4b57d09-a89f-4708-ba62-303401ef6643.png)

although the image links (in this case https://digital.blb-karlsruhe.de/blbhs/content/pageview/1253184) show up just fine over at the library:
![image](https://user-images.githubusercontent.com/67451875/178638059-bdabec70-7527-4385-83ab-5f11d5a8936f.png)

**Comment by dchiller** [comment]
The issue here is the way the diva is dealing with some additional (erroneous?) dimensions in the IIIF manifest.

In this manifest, each page has two dimensions listed, like for this page:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/11023634/179851359-2b75592b-9b06-4648-af63-276e25dad5e9.png">

One set of dimensions is a property of the canvas (the object higher up the hierarchy) and one with a child image. Although I'm not sure I understand the finer points of this differentiation, in general I think the canvas is the entire viewing space and the images might be some child components of that space. In other manifests that are working correctly, there seem to be dimensions only associated with the canvas.

Diva is using the dimension properties of the image, here, which are considerably smaller, leading it to tile only a portion of the canvas (and therefore only a portion of the image).

**Comment by dchiller** [comment]
Should be closed with #532
