### ISSUE TITLE
concordances

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/cantus#521]
The admin page has a list of "concordances" but there is no concordance information available to the users of CU, or at least not obviously. Is this a feature to be added?
(n.b. the information about these particular concordances all lives over at Cantus Index--distinct from the concordances within Cantus DB).

**Comment by dchiller** [comment]
Yes, no concordance data is served publicly ~ don't know what the plan is around that, if any!

Also, not sure if this is known generally, but I'm putting it here because I just discovered it: the concordances that are loaded now are all hardcoded into the Cantus Ultimus source. So they aren't getting updated or added to from any source. Not sure if that's something we ultimately want either?

**Comment by annamorphism** [comment]
after a discussion with Cantus folks, it seems this is a remnant of an older idea, and it was decided not to present any of this information since it can be found elsewhere. (Wondering if it pre-dates the Cantus Index/DB split...)  I feel like there might actually be good ways to incorporate some sort of concordance feature eventually (rather than having to go between a bunch of sites) but it does explain this mystery. Closing this non-issue.
