### ISSUE TITLE
folio suggestion peculiarities

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/cantus#546]
The folio search still does some slightly odd things. 
 
On the one hand, if I type in "3" I get suggestions like 13 and 23, although it's more likely I want something in the 30s or the 300's (if they exist.)  I can live with this though. 
What's odd is that if I type "35" _slowly_  my six suggestions are 35r/v, 135r/v, A35 r/v, but if I type "35" _quickly_ I get 14 results (more than for normal queries), where the eight results for "3" show up in the list and then the 6 for "35". If I toggle back to the tab (as I am doing to write this comment) we are back to the expected 6 results...

It's still a little odd that hitting enter rather than clicking a result takes you to image 35 and not the first suggested page (35r). Then again, if the first suggestion is 3r because of typing too quickly,  I probably don't want to be sent there either...!

**Comment by dchiller** [comment]
Thank you! Clearly some bugs here! 

We can also definitely fine-tune the search suggestions in the direction you note here. I gave almost no thought to the suggestions compared to avoiding the error, so if you have more thoughts about what would make the suggestions better, please keep 'em coming.

**Comment by napulen** [comment]
I just have to say that I admire the diligence of these UX tests, @annamorphism! I'd have never caught that!

In summary, I think we have to issues here that need commits on the code:
- [ ] Make *flushing* of the suggestions quicker to avoid race condition where the results from old query are concatenated with the ones of a new query.
- [ ] Make the first result of the suggestions `focused` by default, so that hitting enter will assume that you meant the top result in the query.

**Comment by dchiller** [comment]
Moving the improvement of search suggestions to a new issue #564, because the two issues mentioned by @napulen above are fixed by #563.
