### ISSUE TITLE
text search doesn't search genre

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/cantus#549]
Although one can search the genre field by itself, "Search all text fields" doesn't seem to actually search genre. For antiphon it gets only 7 results, presumably from the "Feast" field:

![image](https://user-images.githubusercontent.com/67451875/180879716-14ce4017-7223-45fc-b627-c9fb967ffbea.png)

**Comment by annamorphism** [comment]
mysteries: we get 986 results in genre for "responsory verse":
![image](https://user-images.githubusercontent.com/67451875/181283725-c289fa34-e9ff-421c-aa24-33103bed5bd0.png)

but only 184 searching "all fields":
![image](https://user-images.githubusercontent.com/67451875/181283574-b5b0c092-8b08-4d01-8fc1-06abc8a2e80f.png)
They do seem to be responsory verse, but why THESE ones??

**Comment by annamorphism** [comment]
aha! It's the ones where the mode is "Responsory (special)". So Mode gets searched, genre does not. 

Actually the mode search itself is pretty weird too. If you DO want special responsories, and search under Mode, you get quite a lot of stuff that isn't even responsories. Pretty sure it's just searching Mode for the letter R, so includes "UnceRtain" and "FoRmulaic" and "TRansposition". This is very silly.
![image](https://user-images.githubusercontent.com/67451875/181286480-1320362f-21b5-45c6-af9b-afdd155731d3.png)

**Comment by dchiller** [comment]
@annamorphism This issue will be solved by #709. 

What was happening is that we were including all of the other text fields in the fields that were considered by solr during an `All Text Search` search, but for some reason (I don't know if this was a long ago oversight or intentional for some reason at that time -- there's no explanation in the code) `genre` was not one of those fields. Now it will be.

I was also thinking: we have a way to search `All Text Fields` and we have a way to individually search the text fields `genre`, `office`, and `feast` but no way to individually search the chant text itself -- it will only be searched, along with all other fields, in an  `All Text Fields` search. Do you think it makes sense to implement an option to search only the chant text as well? I'm noticing that in CantusDB you can do a search of just the text with all sorts of operators ("starts with", "does not contain", etc) so I am wondering if this should also be considered as part of #700.

**Comment by annamorphism** [comment]
Yes, I think searching chant texts would be useful (consider that you might want to know which texts contain "Jacob" and not get all the ones for the feast of "Jacob"). Many of the operators in CantusDB are not that useful, but "starts with" and "contains" are mighty nice.
