### ISSUE TITLE
Cantus Ultimus has build = error

### ISSUE THREAD

**Issue by dchiller** [DDMAL/cantus#621]

**Comment by dchiller** [comment]
Proposal to get rid of travis ci now that we have up and working github actions.

**Comment by napulen** [comment]
Yes, no reason to keep travis anymore imo.

**Comment by dchiller** [comment]
@napulen I think both this and the coveralls thing require log-ins to those two services. Do you know who would have them? You?

**Comment by napulen** [comment]
Oh, sorry I missed this. Yes, you'd have to bind the service to your personal account. From the perspective of CI, I think it only requires another person in the future (if that's why you are asking) to create an account and change some token in our settings/gh-actions files. So it's not a huge risk to have someone's personal account handling the code coverage for a lab-owned repo.

Personally, I don't have the accounts/ access to code coverage of anything except my own repos (no DDMAL), but I think that's more because most of the DDMAL repos don't have code coverage analysis integrated.

**Comment by napulen** [comment]
I got confused in my previous answer. I thought I was answering a concern about `codecov`. Regarding Travis credentials, I don't have them :(. Why do you need them?

**Comment by dchiller** [comment]
I was trying to get rid of the widget on the readme that says the build failed -- just in case someone comes looking at the repo, and have not been able to figure out how to decouple TravisCI -- but I just removed it from the README, so at least it is no longer visible.

**Comment by napulen** [comment]
AFAIK, travis ci integrates when you
1. Make an account and link your repo within the account
2. Write a `.travis` folder (or just config file?) in the root of the repo

Given that there is no `travis` file/folder (probably I removed it), then the widget is just binded to whatever account had it, but it can safely be removed. So you are good after this change!
