### ISSUE TITLE
Mode search filters are wrong

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/cantus#710]
As described in another issue:

"The mode search itself is pretty weird too. If you DO want special responsories, and search under Mode, you get quite a lot of stuff that isn't even responsories. Pretty sure it's just searching Mode for the letter R, so includes "UnceRtain" and "FoRmulaic" and "TRansposition". This is very silly.
![image](https://user-images.githubusercontent.com/67451875/181286480-1320362f-21b5-45c6-af9b-afdd155731d3.png)

_Originally posted by @annamorphism in https://github.com/DDMAL/cantus/issues/549#issuecomment-1196913461_

**Comment by dchiller** [comment]
Ooo - thank you for breaking this out!

**Comment by dchiller** [comment]
Another mode search issue: when you navigate away and back to a mode search, the previous search is still there (just like the other search types). However, while in other search types the search string repopulates the text input box (so you can see what the search results are for), in mode search the value you previously selected is no longer highlighted....you can figure out what you chose (there are only so many options) but it would be nice if this was consistent.

**Comment by dchiller** [comment]
> Pretty sure it's just searching Mode for the letter R, so includes "UnceRtain" and "FoRmulaic" and "TRansposition"

I've verified that this is the cause ~ the problem is how solr is analyzing the mode field. Currently, we handle `mode` searches differently depending on whether or not the mode we are searching for is a single character (eg. Mode "1", "2", etc.) or many characters (eg. "No music", "Uncertain") (see  https://github.com/DDMAL/cantus/blob/a2006edc58909bf8049eb4666a324aebadff5ca7/nginx/public/node/frontend/public/js/app/search/chant-search/ChantSearchProvider.js#L203). In the second case, the way that the `mode` field is processed for those queries and the way our query string is parsed by solr and means that we only have to match an "r" in the chant's `mode` field to be a match. 

As you say, this doesn't make any sense! We only have 13 possible searches for mode -- the 8 numbered modes and the 5 other mode types ("No Music", etc.). In those 5 latter cases, we should only return chants that have those exact modes. 

Before implementing this, I think we just need to make one decision: should special mode cases also be returned when a number is searched? Some of the special cases (I've seen this thus far for chants with `mode` "Responsory (special)" and "Mode in Transposition") also have a number associated (for example, "4 Mode in Transposition" or "6 Responsory (special): should these be returned when the appropriate number is searched (ie. "Mode 4" and "Mode 6" respectively in these examples)?

**Comment by dchiller** [comment]
> in CantusDB is you search 4 you also get 4S and 4T, and if you search for S you get 1S/2S/3S and so on

Ok, let's continue this in Cantus Ultimus.

> But really it would be better to be able to combine the numbers and some of the other mode types

This also makes sense! 

I will think a bit about the best way to present these possible combinations to the user -- whether that's offering a text box with an explanation of terms elsewhere (the CantusDB way) or by offering some modification of what we currently do (options the user can select).

**Comment by dchiller** [comment]
I am wondering if it would be useful to eventually implement an "Advanced Search" feature in CU -- for example, many libraries and other databases I find myself searching will have a "simple search" feature (a textbox or a few) where you can do a keyword search or directly type in booleans, fields, and the like, and also an "Advanced Search" function that offers you a form to guide you through the process of creating a multi-field search. So, to use the example of the McGill library catalog, it's the difference between these two pages:

![image](https://github.com/DDMAL/cantus/assets/11023634/eca575ac-3360-4f4f-bc45-1a7aa0d764c2)

![image](https://github.com/DDMAL/cantus/assets/11023634/44174dd3-26d6-4ce7-8ad4-9b3b77c23543)

**Comment by annamorphism** [comment]
I like this idea a lot!
