### ISSUE TITLE
Don't commit MEI XML files?

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#77]
The MEI XML files are going to be huge, and should be considered "data" not "code" so we shouldn't be committing them to the repo.

Removing them will also mean rewriting the git history (otherwise we'll keep around a huge amount of data in the changelogs).

This issue is open to discuss this, and to raise any objections.

**Comment by wabain** [comment]
The counterpoint is that versioning the MEI (and CSV) files and having them easily accessible online is extremely useful.

However, the files for the new Salzinnes data are too large for me to want to commit them. The MEI is ~3x the size of all the existing MEI, and the new CSV file is ~42x (!!) the size of the existing CSV data (there's a lot of redundant data for each row). For now, I've checked the data into a local branch, and I won't be pushing it to Github.

Also, I don't think it would be worth rewriting git history since relatively speaking what's been committed so far isn't actually all that large and git performance has been fine. But this is something we'll need to work out going forward.

**Comment by wabain** [comment]
For consideration: https://github.com/blog/1986-announcing-git-large-file-storage-lfs

**Comment by ahankinson** [comment]
I have signed us up for LFS a couple months ago but am still waiting to be given access to the beta program.

**Comment by napulen** [comment]
In the next iteration of the website, there is no need to add `csv` files to version control. Regarding MEI, I believe that won't be the case as well.
